In [1]:
from __future__ import print_function
import torch  as t

In [11]:
a = t.randn(3,4,requires_grad=True)
a

tensor([[-0.7337, -0.0806, -1.7640, -0.1874],
        [-0.9139, -0.2348,  0.8586, -1.4445],
        [ 1.3759,  1.0120, -0.6989,  1.6567]], requires_grad=True)

In [16]:
b = t.zeros_like(a,requires_grad=True)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], requires_grad=True)

In [17]:
c = a.add(b)
c

tensor([[-0.7337, -0.0806, -1.7640, -0.1874],
        [-0.9139, -0.2348,  0.8586, -1.4445],
        [ 1.3759,  1.0120, -0.6989,  1.6567]], grad_fn=<AddBackward0>)

In [19]:
d = c.sum()
d

tensor(-1.1546, grad_fn=<SumBackward0>)

In [24]:
d.backward()

In [25]:
a.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

计算下面这个函数的导函数：
$$
y = x^2\bullet e^x
$$
它的导函数是：
$$
{dy \over dx} = 2x\bullet e^x + x^2 \bullet e^x
$$

In [49]:
def f(x):
    y = x**2*t.exp(x)
    return y

def gradf(x):
    dx = 2*x*t.exp(x) + x**2*t.exp(x)
    return dx

In [50]:
x = t.randn(3,4, requires_grad = True)
y = f(x)
y

tensor([[4.0656e+00, 6.8466e+01, 3.6887e-02, 3.0146e-01],
        [2.8267e-01, 5.1265e-02, 5.1456e+01, 1.0643e+01],
        [3.5651e-01, 5.4133e-01, 1.9386e-04, 1.3438e-02]],
       grad_fn=<MulBackward0>)

In [51]:
y.backward(t.ones(y.size()))
x.grad

tensor([[ 1.1197e+01,  1.2456e+02, -3.0830e-01,  1.6701e+00],
        [-4.3415e-01, -3.4686e-01,  9.6462e+01,  2.4617e+01],
        [-3.7890e-01,  2.0670e-03,  2.8233e-02, -2.0454e-01]])

In [52]:
gradf(x)

tensor([[ 1.1197e+01,  1.2456e+02, -3.0830e-01,  1.6701e+00],
        [-4.3415e-01, -3.4686e-01,  9.6462e+01,  2.4617e+01],
        [-3.7890e-01,  2.0670e-03,  2.8233e-02, -2.0454e-01]],
       grad_fn=<AddBackward0>)