In [2]:
 from __future__ import print_function
import torch as t

t.__version__

'1.7.1'

In [ ]:
x = t.Tensor(5,3) # 只是分配了空间，未初始化
x = t.Tensor([
    [1,2],
    [3,4]
])
x

In [11]:
x = t.rand(5,3)
x

tensor([[0.5985, 0.0230, 0.1300],
        [0.2469, 0.2007, 0.3022],
        [0.5196, 0.9757, 0.1823],
        [0.9893, 0.9305, 0.3457],
        [0.9208, 0.7818, 0.3827]])

In [52]:
print(x.size())
x.size(1)

torch.Size([5, 3])


3

**注意，函数名后面带下划线_ 的函数会修改Tensor本身。例如，x.add_(y)和x.t_()会改变 x，但x.add(y)和x.t()返回一个新的Tensor， 而x不变**

In [18]:
y = t.rand(5, 3)

print('最初y')
print(y)

print('第一种加法，y的结果')
y.add(x) # 普通加法，不改变y的内容
print(y)

print('第二种加法，y的结果')
y.add_(x) # inplace 加法，y变了
print(y)

最初y
tensor([[0.1884, 0.4089, 0.7402],
        [0.2582, 0.7942, 0.1672],
        [0.1954, 0.2684, 0.6839],
        [0.8902, 0.6710, 0.4190],
        [0.7259, 0.4828, 0.3932]])
第一种加法，y的结果
tensor([[0.1884, 0.4089, 0.7402],
        [0.2582, 0.7942, 0.1672],
        [0.1954, 0.2684, 0.6839],
        [0.8902, 0.6710, 0.4190],
        [0.7259, 0.4828, 0.3932]])
第二种加法，y的结果
tensor([[0.7869, 0.4319, 0.8702],
        [0.5052, 0.9948, 0.4694],
        [0.7149, 1.2441, 0.8661],
        [1.8794, 1.6015, 0.7648],
        [1.6468, 1.2645, 0.7758]])


In [21]:
a = t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [23]:
b = a.numpy() # Tensor -> Numpy
b

array([1., 1., 1., 1., 1.], dtype=float32)

**Tensor和numpy对象共享内存，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另外一个也会随之改变**

In [44]:
import numpy as np 
a = np.ones(5,dtype=int)
b = t.from_numpy(a) # Numpy->Tensor
print(a)
print(b)

[1 1 1 1 1]
tensor([1, 1, 1, 1, 1], dtype=torch.int32)


In [30]:
b.add_(1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**获取某一个元素item()**

In [37]:
scalar = b[0]
scalar,scalar.size() #0-dim

(tensor(2., dtype=torch.float64), torch.Size([]))

In [38]:
scalar.item() # 使用scalar.item()能从中取出python对象的数值

2.0

In [41]:
tensor = t.tensor([2]) # tensor和scalar
tensor,scalar

(tensor([2]), tensor(2., dtype=torch.float64))

In [42]:
tensor.item(), scalar.item()  # 只有一个元素的tensor也可以调用`tensor.item()`

(2, 2.0)

In [46]:
old_tensor = t.tensor([3,4])
new_tensor_1 = old_tensor.clone() # tensor.clone(）不会共享内存
new_tensor_1[0] = 1111
new_tensor_2 = old_tensor.detach() # tensor.detach(）会共享内存（from_numpy也会）
new_tensor_2[0] = 2222
old_tensor,new_tensor_1,new_tensor_2

(tensor([2222,    4]), tensor([1111,    4]), tensor([2222,    4]))

**Tensor可通过.cuda 方法转为GPU的Tensor，从而享受GPU带来的加速运算**

In [51]:
device = t.device('cuda:0' if t.cuda.is_available() else 'cpu')
x = t.rand(5,3).to(device)
y = t.rand(5,3).to(device)
z = x + y
device,z

(device(type='cuda', index=0),
 tensor([[0.5661, 1.5849, 1.1251],
         [1.4555, 1.2796, 0.8060],
         [1.1277, 0.3578, 0.4325],
         [1.0149, 0.8478, 0.3719],
         [0.3315, 0.4857, 1.6536]], device='cuda:0'))